### ISSUE TITLE
Add a comparison to the builtin base64.b64encode

### ISSUE THREAD

**Issue by eric-wieser** [hatgit/hatnotation#9]
It's not clear to me why I would want to use this over the builtin python [`base64`](https://docs.python.org/3/library/base64.html) module:

```python
>>> base64.b64encode(b'test')
b'dGVzdA=='
>>> base64.b64decode(b'dGVzdA==')
b'test'
```
Or on arbitrary bytes:
```
>>> base64.b64encode(bytes([1, 2, 3]))
b'AQID'
>>> list(base64.b64decode(b'AQID'))
[1, 2, 3]
```

Can you include base64 in your comparison tables?

**Comment by hatgit** [comment]
Hi Eric, thanks for the idea. When I created this it wasn't meant to replace or compete with base64 (I actually learned about base64 afterward) as it was just an experiment, so the only similarity is the length of the library. In addition, Hatnotation deals with binary integers, whereas, base64 requires a bytes object else produces the error `TypeError: a bytes-like object is required, not 'int'`, although perhaps there are other commands in the dir(base64) library that can deal with other data formats, not sure.

I just added an example comparison to the Read.me file as a result of your suggestion ([Here is the commit](https://github.com/hatgit/hatnotation/commit/dec293114599e9ed5961b0aac3cbe270501f442a#diff-04c6e90faac2675aa89e2176d2eec7d8)), using the existing 132-bit binary string already in the Read.me but converted to a bytearray.

**As 132-bit binary 0b-padded:** 
`0b000010011001110010111111101011110001001100000011001001110111011010111000001111100110001101001100001011000010111010100000000101111110`

**As 22-character Hatnotation with no padding:**
2P{`(.C39>Q?F#DCB2[W5_

**Binary converted to Hex, then to 16 bytes totalling 35 characters excluding backslahes and b- pad:** 
b'\x99\xcb\xfa\xf102wk\x83\xe64\xc2\xc2\xea\x01~'

**Base64 totalling 24-characters excluding b-pad:**
`b'mcv68TAyd2uD5jTCwuoBfg=='`

**Comment by eric-wieser** [comment]
What you're referring to as "b-pad" is not part of the string any more than the quotes are - it's Python3's way of telling you you're looking at raw bytes which may or may not be human readable.

**Comment by hatgit** [comment]
Hi @eric-wieser, do you have any other feedback or suggestions before I close this issue? I appreciate you taking the time to chime in here. Thanks.

**Comment by eric-wieser** [comment]
Yes, I suggest you completely remove the phrase `b-pad` from your readme
